services:
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_STRAPI_URL: http://75.119.135.164:9001
    ports:
      - "9002:9002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NEXT_PUBLIC_STRAPI_URL=http://75.119.135.164:9001
    restart: unless-stopped
