version: "3.9"

services:
  sidago-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidago-frontend
    env_file:
      - .env
    ports:
      - "9002:9002"
    restart: always